### ISSUE TITLE
Doesn't compile under NixOS

### ISSUE THREAD

**Issue by Qubasa** [flatironinstitute/nixpack#10]
I did the following:
```bash
$ git clone https://github.com/flatironinstitute/nixpack.git
$ cd nixpack
$ nix-build -A spackRepo
/nix/store/w2ll9a0j9g48sklzac68rfgvynxw1qhn-install.sh: line 2: /bin/mkdir: not found
```

```
$ nix-info   
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.4, channels(mjnam): "", channels(harshanavkis): "home-manager-21.05", channels(root): "nix-ld, nixos-21.05.4448.4a8751d694b", nixpkgs: /nix/store/8hd2049cr4dz9myjcjjh6cjjapz1p107-source
```

**Comment by dylex** [comment]
Yeah, there's a lot of hard-coded /bin paths throughout nixpack. (#8 takes a step to fix a few of these, but not all.) We could go fix these more systematically to use some passed path, and theoretically you could point these to an environment with the needed things (sh, coreutils, python, gcc). This would still violate purity, but that's kind of the nature of spack.

A more radical option, which I considered initially, is to host nixpack/spack on nixpkgs, so all these needed things are built from nixpkgs automatically, but you'd still need a bootstrap compiler, and using the nix compiler would defeat our purpose for using spack to begin with (i.e., to be able to use system libraries).

I suppose the point is that the solution really depends on your use case.  Just providing a path and passing that around is probably the simplest solution.

**Comment by dguibert** [comment]
this has been solved in commit https://github.com/flatironinstitute/nixpack/pull/8/commits/796e1765fc0d1fd41f07c19c8b9ef306fb64e70f

**Comment by Qubasa** [comment]
I see, thanks everyone!
