### ISSUE TITLE
Support `autoload=direct` (or !=none or prerequisite!=none) within pack.modules

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#14]
Hi,

I'm trying to set up a module tree with `pack.modules` and setting `autoload=direct` to get all the modules needed.
I tried to hack on `adddeps` to filter specs on their deptype, it work pretty well as I get the list of the needed modules but for extern package their full name are not set correctly:
````
modules>   linux-rhel8-x86_64/Core/openssh/8.0p1.lua: openssh@8.0p1%gcc@0 patches=86ab7e64dd0ae7dd0fa1077bc271fa9bd1289d555f70a5e25beacba4b8c4b051 arch=linux-rhel8-x86_64 /usr
modules>   linux-rhel8-x86_64/Core/rdma-core/34.0.lua: rdma-core@34.0%gcc@8.4.1~ipo build_type=RelWithDebInfo arch=linux-rhel8-x86_64 /nix/store/rlw0ba7m6ap3q6x6mngj8qdm671sifsk-rdma-core-34.0
modules>   linux-rhel8-x86_64/Core/openssh/8.0p1.lua: slurm@19.05%gcc@0~gtk~hdf5+hwloc~mariadb~pmix+readline~restd sysconfdir=PREFIX/etc arch=linux-rhel8-x86_64 /usr
modules> ==> Warning: Module file /nix/store/z5ciynpbdjqlhc9pvhqr8a7jbmis5c99-modules/linux-rhel8-x86_64/Core/openssh/8.0p1.lua exists and will not be overwritten
modules> Traceback (most recent call last):
modules>   File "/nix/store/jzjfbpnhlgyxynzvm34nvc7ws0gp7ipc-modules.py", line 198, in <module>
modules>     assert fn not in seen, f"Duplicate path: {fn}"
modules> AssertionError: Duplicate path:/nix/store/z5ciynpbdjqlhc9pvhqr8a7jbmis5c99-modules/linux-rhel8-x86_64/Core/openssh/8.0p1.lua
````

Openssh module is being overriden by the slum module.

**Comment by dylex** [comment]
This seems like a problem with the projections that it's deciding to name the slum module openssh.  Is this specific to autoload=direct?  Like if you set it to none does this not happen?

**Comment by dguibert** [comment]
Thx @dylex, there is a problem with the projections.
It is not directly specific to autoload=direct as I have implemented this feature on top of packs.modules so that the pkgs attribute gets all the packages needed for autoload=direct to work when any module is loaded.

I basically developped:
````nix
      lib.findModDeps = pkgs: with inputs.nixpack.lib; with builtins; let
          mods = map (x: addPkg x) pkgs;
          addPkg = x: if x ? spec
                      then if x.spec.extern == null then { pkg=x; }
                                                    else builtins.trace "addPkg: ${nixpkgs.lib.generators.toPretty { allowPrettyValues=true; } x.spec}"
                                                         { pkg=x; projection="${x.spec.name}/${x.spec.version}"; }
                      else x;
          pred = x: (isRLDep (x.pkg.deptype or []));

          pkgOrSpec = p: p.pkg.spec or p;
          adddeps = s: pkgs: add s
          (filter (p: builtins.trace "adddeps: ${nixpkgs.lib.generators.toPretty { allowPrettyValues = true; } p}"
                         p != null
                      && ! (any (x: pkgOrSpec x == pkgOrSpec p) s)
                      && pred p)
              (nubBy (x: y: pkgOrSpec x == pkgOrSpec y)
                     (concatMap (p: map (x: addPkg x)
                                        (attrValues (p.pkg.spec.depends or {}))
                                )
                  pkgs)
              )
            );
            add = s: pkgs: if pkgs == [] then s else adddeps (s ++ pkgs) pkgs;
          in add [] (toList mods);
````
and
````nix
          mkModules = pack: pkgs: pack.modules (inputs.nixpack.lib.recursiveUpdate modulesConfig ({
            coreCompilers = [ final.bootstrapPacks.pkgs.compiler ];
            pkgs = self.lib.findModDeps pkgs;
          }));
````

**Comment by dylex** [comment]
Does that `addPkg` trace have any clues for slurm? If you do `mkModules pack [slurm]` by itself does it get the right name? If you set `projection="{name}/{version}"` for the externs (the default probably) does that change anything?

**Comment by dguibert** [comment]
no clues with the `addPkg` trace.
Only one package in mkModules gets its right name.

How can `projection="{name}/{version}"` be set for externs?

To be clear, the function `mkModules` I posted works as expected.

**Comment by dylex** [comment]
As long as the package is something spack knows about, projections with variables still work fine. You're still expected to tell spack the version, variants, etc of the extern when you configure it (so dependencies work right). For example, this is our slurm extern package projection, which works fine: https://github.com/flatironinstitute/nixpack/blob/main/fi/default.nix#L1164
So I'm curious if this issue is because the projection config is being consumed incorrectly with the hard-coded name.

**Comment by dguibert** [comment]
Is your slurm module still generated correctly if you remove  https://github.com/flatironinstitute/nixpack/blob/528a3058d2c29f508fd66c1aeb2d1beee22b19d3/fi/default.nix#L1165 ?

**Comment by dguibert** [comment]
as https://github.com/flatironinstitute/nixpack/issues/14#issuecomment-1090536823 contains a solution to this issue, I'm closing it.
