### ISSUE TITLE
Evaluation fails with new fi-nixpack revision

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#3]
Hi, great project loving it ;-)

While I'm playing with it your spack repo  has been updated from 9526a13086fbc1790814edb84cdd9b65dbfc8f90 to 2311242d266d90726222002a262b50a165adb6bf.
It evaluates on the first revision but it fails on the second with the following error:
````
spack-repo.nix> Generating package repo for nixpack, builtin...
spack-repo.nix> Traceback (most recent call last):
spack-repo.nix>   File "/home_nfs/bguibertd/nix/store/p0qs23rqkqgsz799h53rhpx6qrszi3g7-generate.py", line 264, in <module>
spack-repo.nix>     desc['variants'] = {n: variant(p, v) for n, v in p.variants.items()}
spack-repo.nix>   File "/home_nfs/bguibertd/nix/store/p0qs23rqkqgsz799h53rhpx6qrszi3g7-generate.py", line 264, in <dictcomp>
spack-repo.nix>     desc['variants'] = {n: variant(p, v) for n, v in p.variants.items()}
spack-repo.nix>   File "/home_nfs/bguibertd/nix/store/p0qs23rqkqgsz799h53rhpx6qrszi3g7-generate.py", line 156, in variant
spack-repo.nix>     d = str(v.default)
spack-repo.nix> AttributeError: 'tuple' object has no attribute 'default'
````

**Comment by dylex** [comment]
Hey, sorry, just noticed this, and actually ended up fixing it myself independently in essentially the same way (just with backwards compatibility).  Still need to figure out the best way to handle the new when (i.e., expose the conditional variant based on the condition), but this temporary fix of ignoring the conditional should be fine for now.

Glad to hear this is useful to you.  We're now using it in production so certainly plan to keep maintaining it (though a lot of our changes have been going into our `fi` directory).  Happy to entertain any feedback or things that would make it more useful.
