### ISSUE TITLE
Flakes support?

### ISSUE THREAD

**Issue by Qubasa** [flatironinstitute/nixpack#9]
Hi there,

I wanted to ask if there are plans to adopt [flakes](https://www.tweag.io/blog/2020-05-25-flakes/) support?
That would be really awesome!

Cheers

**Comment by dylex** [comment]
nix flakes definitely seem like a nice idea and would fit well. I know @dguibert has done some work on this with #8, though I haven't looked too closely at it yet.  I was sort of waiting until they became less experimental (specifically made it into a stable nix release on a stable nixpkgs release) before looking at switching over to them.

**Comment by dguibert** [comment]
Hi,
@Luis-Hebendanz you could use my PR to test the flake support.
@dylex the flake support is pretty stable but still marked as experimental, you can view it as a declarative definition of NIX_PATH or channels.

**Comment by Qubasa** [comment]
@dguibert Awesome! I will try it out!

**Comment by Qubasa** [comment]
@dguibert How do I import that into a nixos flake configuration? I tried
```
inputs.nixpack.url = "github:dguibert/nixpack/dg/flake";

outputs = {self, nixpack}: {
        nixosConfigurations.my-desktop = nixpkgs.lib.nixosSystem {
            system = "x86_64-linux";
          ({ ... }: {
          nixpkgs.config = {
            allowUnfree = true;
            packageOverrides = pkgs:
            {
              nixpack = import (nixpack.packages)
              {
                system = "x86_64-linux";
              };
            }
           }
         }
     }
}
```

**Comment by dguibert** [comment]
> @dguibert How do I import that into a nixos flake configuration

Which issue do you face? See my PR description, the options `--impure --option sandbox false`  are required.

To use it, I assume that into `environment.systemPackages`, you can put `nixpack.pkgs.$package` but this will use the basic nixosPack defined into the flake.

**Comment by dguibert** [comment]
I see, try using `nixpack = nixpack.packages.x86_64-linux;`

**Comment by Qubasa** [comment]
@dguibert Thanks, that was it!
